name: Daily Auto Commit

on:
  schedule:
    # Roda todos os dias ao meio-dia (UTC)
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite que você clique em "Run workflow" para testar manualmente

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão obrigatória para o GitHub Actions poder fazer o push

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Fazer uma alteração no arquivo
        run: |
          # Cria ou atualiza um arquivo chamado keep-alive.txt com a data atual
          echo "Último commit automático gerado em: $(date)" > keep-alive.txt

      - name: Configurar o Git e fazer o Commit
        run: |
          git config --local user.email "mateushoffmandev@gmail.com"
          git config --local user.name "Mateus Hoffman"
          git add keep-alive.txt
          git commit -m "chore: commit automático" || echo "Nenhuma mudança para commitar"
          git push
